(()=>{'use strict';const D=window.Dino={};D.W=960;D.H=540;D.G=438;D.TAU=Math.PI*2;D.$=id=>document.getElementById(id);D.rnd=(a,b)=>a+Math.random()*(b-a);D.pick=a=>a[Math.floor(Math.random()*a.length)];D.clamp=(v,a,b)=>Math.max(a,Math.min(b,v));D.hit=(a,b)=>a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y;D.store={get(k,f){try{const v=localStorage.getItem(k);return v===null?f:JSON.parse(v)}catch{return f}},set(k,v){try{localStorage.setItem(k,JSON.stringify(v))}catch{}}};
D.worlds=[
{name:'Prehistoric Backyard',short:'Backyard',sky1:'#84d8f4',sky2:'#dff8ff',ground:'#73bf5d',dirt:'#4f8d45',accent:'#ffc857',obs:['cat','tree','duck','pizza']},
{name:'Cat Nap Forest',short:'Cat Forest',sky1:'#77c7af',sky2:'#d7f5cf',ground:'#3f9257',dirt:'#2d6c43',accent:'#a7e36c',obs:['cat','stump','yarn','tree']},
{name:'Kitchen Chaos',short:'Kitchen',sky1:'#ffd8a5',sky2:'#fff0d0',ground:'#d99753',dirt:'#b46c35',accent:'#ff775f',obs:['pizza','toast','mixer','roll']},
{name:'Living Room Rampage',short:'Living Room',sky1:'#bca7ee',sky2:'#eee4ff',ground:'#8f6cba',dirt:'#694b91',accent:'#79f0f2',obs:['vacuum','lamp','cat','yarn']},
{name:"Sir Whiskers' Castle",short:'Cat Castle',sky1:'#3f3b79',sky2:'#9a6db4',ground:'#4d426b',dirt:'#2e2946',accent:'#ffcb5a',obs:['armorCat','banner','crown','cat']}
];
D.skins={jungle:{body:'#49bd68',dark:'#257843',belly:'#d8f0a8',stripe:'#14613a',bandana:'#ef4f4f'},ocean:{body:'#3aaed8',dark:'#176a92',belly:'#c7f3ee',stripe:'#15547a',bandana:'#ffcf4a'},sunset:{body:'#ed8a45',dark:'#9b492e',belly:'#ffe1a6',stripe:'#7d3627',bandana:'#754ad8'}};
D.powerInfo={flame:['Flame Breath',0],laser:['Laser Blaster',0],shield:['Shield Egg',0],sneakers:['Super Sneakers',7],magnet:['Star Magnet',8],freeze:['Time Freeze',6],golden:['Golden Rex',6],roar:['Mega Roar',0],life:['Extra Life',0],star:['Bonus Star',8]};
D.achievements=[['first','First Footprints','Start your first adventure.'],['cats','Cat Nap Champion','Jump over 10 sleeping cats.'],['wreck','Wrecking Rex','Destroy 25 obstacles.'],['combo','Combo Carnivore','Reach an x8 combo.'],['kitchen','Kitchen Invader','Reach Kitchen Chaos.'],['collector','Power Hungry','Collect 8 powers in one run.'],['roar','Roar Authority','Clear 5 hazards with one Mega Roar.'],['score','Ten Thousand Teeth','Score 10,000 points.'],['cleanBoss','Untouchable Rex','Defeat Sir Whiskers without boss damage.'],['boss','King of the Backyard','Defeat Sir Whiskers.']];
D.missions=[['jump',10,'Jump 10 hazards'],['destroy',12,'Destroy 12 hazards'],['star',6,'Collect 6 stars'],['power',5,'Collect 5 powers'],['close',4,'Make 4 close calls']];
D.ui={};D.arrays={obstacles:[],items:[],shots:[],enemies:[],particles:[],floaters:[]};
const dailyKey=new Date().toISOString().slice(0,10);const inferredWorld=Math.min(4,Math.floor(D.store.get('dinoCatDashHighScore',0)/2200));D.state={mode:'menu',last:0,time:0,score:0,lives:3,speed:360,world:0,worldBanner:0,boss:null,spawn:1,itemSpawn:4,starSpawn:3,combo:1,comboTime:0,high:D.store.get('dinoCatDashHighScore',0),bestCombo:D.store.get('dinoCatDashBestCombo',1),unlocked:new Set(D.store.get('dinoCatDashAchievements',[])),skin:D.store.get('dinoCatDashSkin','jungle'),maxWorld:Math.max(inferredWorld,D.store.get('dinoCatDashMaxWorld',0)),selectedWorld:0,dailyKey,dailyBest:D.store.get('dinoCatDashDaily-'+dailyKey,0),sound:D.store.get('dinoCatDashSound',true),music:D.store.get('dinoCatDashMusic',true),toast:0,shake:0,flash:0,menuMode:'main',mission:D.missions[0],missionValue:0,stats:{},musicBeat:0,musicStep:0};
D.player={x:118,y:D.G-92,w:104,h:92,vy:0,ground:true,inv:0,power:'none',ammo:0,cool:0,timed:'none',timedMax:0,timedLeft:0,shield:0,roars:0,anim:'idle',animTime:0,attackTime:0};
D.resetStats=()=>{D.state.stats={jumps:0,destroyed:0,stars:0,powers:0,close:0,cats:0,bossDamage:0,worldDamage:0,distance:0,maxCombo:1,missionDone:false};let hash=0;for(const ch of D.state.dailyKey)hash=(hash*31+ch.charCodeAt(0))>>>0;D.state.mission=D.missions[hash%D.missions.length];D.state.missionValue=0};D.resetStats();
})();
