(()=>{
'use strict';
const canvas=document.getElementById('game'),ctx=canvas.getContext('2d');
const W=960,H=540,G=438,GOAL=2500;
const $=id=>document.getElementById(id);
const ui={score:$('score'),high:$('high'),lives:$('lives'),power:$('power'),speed:$('speed'),progressText:$('progressText'),progressBar:$('progressBar'),toast:$('toast'),overlay:$('overlay'),title:$('overlayTitle'),message:$('overlayMessage'),start:$('startBtn'),jump:$('jumpBtn'),shoot:$('shootBtn'),roar:$('roarBtn'),pause:$('pauseBtn'),instructions:$('instructions'),sound:$('soundBtn')};
const assetPaths={rexJump:'assets/rex-jump.b64',cat:'assets/sleeping-cat.b64',duck:'assets/rubber-duck.b64',stump:'assets/tree-stump.b64',pizza:'assets/pizza-slice.b64',tree:'assets/tall-tree.b64'};
const images={};let assetsReady=false;
Promise.all(Object.entries(assetPaths).map(async([key,src])=>{try{const raw=await fetch(src,{cache:'no-store'}).then(r=>{if(!r.ok)throw new Error(src);return r.text()});await new Promise(resolve=>{const im=new Image();im.onload=()=>{images[key]=im;resolve()};im.onerror=resolve;im.src='data:image/webp;base64,'+raw.trim()})}catch{}})).then(()=>assetsReady=true);
const obstacleDefs={
 cat:{image:'cat',w:142,h:80,padX:19,padY:21,score:120},
 duck:{image:'duck',w:92,h:86,padX:16,padY:17,score:130},
 stump:{image:'stump',w:128,h:86,padX:13,padY:17,score:145},
 pizza:{image:'pizza',w:108,h:80,padX:14,padY:15,score:140},
 tree:{image:'tree',w:108,h:158,padX:20,padY:18,score:185}
};
const state={mode:'menu',last:0,time:0,score:0,high:Number(localStorage.getItem('rexRemixHigh')||0),lives:5,speed:310,spawn:1.4,itemSpawn:6,objects:[],items:[],shots:[],particles:[],floaters:[],sound:localStorage.getItem('rexRemixSound')!=='false',distance:0,toastTime:0,won:false};
const player={x:105,y:G-126,w:146,h:126,vy:0,ground:true,inv:0,shield:0,laser:0,roars:0,hold:false,holdTime:0,anim:0};
let audioCtx=null;
function tone(freq=300,dur=.08,type='sine',vol=.04){if(!state.sound)return;try{audioCtx ||= new (window.AudioContext||window.webkitAudioContext)();const o=audioCtx.createOscillator(),g=audioCtx.createGain();o.type=type;o.frequency.value=freq;g.gain.value=vol;o.connect(g);g.connect(audioCtx.destination);o.start();g.gain.exponentialRampToValueAtTime(.001,audioCtx.currentTime+dur);o.stop(audioCtx.currentTime+dur)}catch{}}
function toast(text){ui.toast.textContent=text;ui.toast.classList.add('show');state.toastTime=2.2}
function reset(){state.mode='play';state.time=0;state.score=0;state.lives=5;state.speed=310;state.spawn=1.5;state.itemSpawn=5;state.objects.length=state.items.length=state.shots.length=state.particles.length=state.floaters.length=0;state.distance=0;state.won=false;Object.assign(player,{y:G-player.h,vy:0,ground:true,inv:0,shield:0,laser:0,roars:0,hold:false,holdTime:0});ui.overlay.classList.remove('visible');updateHud();state.last=performance.now();tone(420,.12,'triangle')}
function showOverlay(title,message,button='Play Again'){state.mode='over';ui.title.textContent=title;ui.message.textContent=message;ui.start.textContent=button;ui.overlay.classList.add('visible')}
function updateHud(){ui.score.textContent=Math.floor(state.score).toLocaleString();ui.high.textContent=Math.max(state.high,Math.floor(state.score)).toLocaleString();ui.lives.textContent='❤'.repeat(Math.max(0,state.lives))||'0';ui.lives.setAttribute('aria-label',`${state.lives} lives`);ui.power.textContent=player.laser?`Laser ${player.laser}`:player.shield?'Shield':player.roars?`Roar ${player.roars}`:'None';ui.speed.textContent=state.speed<350?'Warm-Up':state.speed<405?'Picking Up':state.speed<455?'Fast':'Wild';ui.progressText.textContent=`Backyard Run: ${Math.min(GOAL,Math.floor(state.score)).toLocaleString()} / ${GOAL.toLocaleString()}`;ui.progressBar.style.width=`${Math.min(100,state.score/GOAL*100)}%`;ui.shoot.disabled=player.laser<1||state.mode!=='play';ui.roar.disabled=player.roars<1||state.mode!=='play';ui.pause.textContent=state.mode==='pause'?'Resume':'Pause'}
function jump(){if(state.mode!=='play')return;if(player.ground){player.vy=-760;player.ground=false;player.holdTime=0;tone(520,.08,'square');spawnDust(player.x+35,G-6,7)}}
function jumpDown(){player.hold=true;jump()}
function jumpUp(){player.hold=false;if(player.vy<-320)player.vy*=.58}
function shoot(){if(state.mode!=='play'||player.laser<1)return;player.laser--;state.shots.push({x:player.x+105,y:player.y+42,w:52,h:10,vx:980,life:1.4});tone(780,.07,'sawtooth');updateHud()}
function roar(){if(state.mode!=='play'||player.roars<1)return;player.roars--;let cleared=0;for(const o of state.objects){burst(o.x+o.w/2,o.y+o.h/2,'#ffe066',16);cleared++;state.score+=90}state.objects.length=0;toast(`Mega Roar cleared ${cleared} obstacle${cleared===1?'':'s'}`);tone(115,.35,'sawtooth',.07);updateHud()}
function pause(){if(state.mode==='play'){state.mode='pause';ui.title.textContent='Paused';ui.message.textContent='Rex is waiting. Resume when ready.';ui.start.textContent='Resume';ui.overlay.classList.add('visible')}else if(state.mode==='pause'){state.mode='play';state.last=performance.now();ui.overlay.classList.remove('visible')}updateHud()}
function spawnObstacle(){const pool=state.time<18?['cat','duck','pizza','stump']:state.time<40?['cat','duck','pizza','stump','tree']:['cat','duck','stump','pizza','tree','tree'];const type=pool[Math.floor(Math.random()*pool.length)],d=obstacleDefs[type];state.objects.push({type,x:W+30,y:G-d.h,w:d.w,h:d.h,phase:Math.random()*Math.PI*2,passed:false});const minGap=state.time<20?1.55:1.25,maxGap=state.time<20?2.25:1.9;state.spawn=minGap+Math.random()*(maxGap-minGap)+(type==='tree'?.35:0)}
function spawnItem(){const r=Math.random();const kind=r<.35?'star':r<.6?'shield':r<.84?'laser':'roar';state.items.push({kind,x:W+30,y:250+Math.random()*105,w:74,h:70,phase:Math.random()*6});state.itemSpawn=5.7+Math.random()*4.2}
function playerBox(){return{x:player.x+32,y:player.y+20,w:player.w-62,h:player.h-28}}
function objectBox(o){const d=obstacleDefs[o.type];return{x:o.x+d.padX,y:o.y+d.padY,w:o.w-d.padX*2,h:o.h-d.padY}}
function hit(a,b){return a.x<b.x+b.w&&a.x+a.w>b.x&&a.y<b.y+b.h&&a.y+a.h>b.y}
function damage(){if(player.inv>0)return;if(player.shield){player.shield=0;player.inv=1.2;toast('Shield blocked the obstacle');tone(220,.18,'triangle');return}state.lives--;player.inv=2;toast('Obstacle hit — recovery shield active');tone(120,.2,'sawtooth');if(state.lives<=0){state.high=Math.max(state.high,Math.floor(state.score));localStorage.setItem('rexRemixHigh',state.high);showOverlay('Rex Needs Another Run',`Score: ${Math.floor(state.score).toLocaleString()}. The illustrated obstacles are clearer, but Rex still needs your timing.`)}updateHud()}
function collect(it){if(it.kind==='star'){state.score+=180;floatText('+180 STAR',it.x,it.y,'#fff38a');tone(680,.09,'triangle')}else if(it.kind==='shield'){player.shield=1;toast('Shield collected');tone(480,.12,'sine')}else if(it.kind==='laser'){player.laser=Math.min(30,player.laser+12);toast('Laser collected — Shoot is ready');tone(760,.1,'square')}else{player.roars=Math.min(3,player.roars+1);toast('Mega Roar collected');tone(180,.22,'sawtooth')}updateHud()}
function burst(x,y,color,count=10){for(let i=0;i<count;i++)state.particles.push({x,y,vx:(Math.random()-.5)*320,vy:-80-Math.random()*220,life:.45+Math.random()*.45,color,size:3+Math.random()*6})}
function spawnDust(x,y,count=4){for(let i=0;i<count;i++)state.particles.push({x:x+Math.random()*18,y:y-Math.random()*6,vx:-20-Math.random()*70,vy:-15-Math.random()*60,life:.25+Math.random()*.3,color:'rgba(255,255,255,.65)',size:4+Math.random()*6})}
function floatText(text,x,y,color){state.floaters.push({text,x,y,life:1,vy:-45,color})}
function update(dt){if(state.toastTime>0){state.toastTime-=dt;if(state.toastTime<=0)ui.toast.classList.remove('show')}if(state.mode!=='play')return;state.time+=dt;state.distance+=state.speed*dt;state.score+=dt*17;state.speed=Math.min(480,310+state.time*3.2);player.inv=Math.max(0,player.inv-dt);player.anim+=dt;player.vy+=2320*dt;if(player.hold&&!player.ground&&player.vy<0&&player.holdTime<.11){player.vy-=720*dt;player.holdTime+=dt}player.y+=player.vy*dt;if(player.y>=G-player.h){if(!player.ground&&player.vy>300){tone(180,.05,'triangle');spawnDust(player.x+38,G-5,5)}player.y=G-player.h;player.vy=0;player.ground=true}
 state.spawn-=dt;state.itemSpawn-=dt;if(state.spawn<=0)spawnObstacle();if(state.itemSpawn<=0)spawnItem();
 for(const o of state.objects){o.x-=state.speed*dt;o.phase+=dt*3}for(const it of state.items){it.x-=state.speed*.82*dt;it.phase+=dt*4}for(const s of state.shots){s.x+=s.vx*dt;s.life-=dt}
 const pb=playerBox();for(let i=state.objects.length-1;i>=0;i--){const o=state.objects[i];if(hit(pb,objectBox(o))){damage();state.objects.splice(i,1);continue}if(!o.passed&&o.x+o.w<player.x){o.passed=true;state.score+=obstacleDefs[o.type].score;floatText(`+${obstacleDefs[o.type].score}`,o.x,o.y,'#fff');tone(390,.04,'triangle')}if(o.x+o.w<-40)state.objects.splice(i,1)}
 for(let i=state.items.length-1;i>=0;i--){const it=state.items[i];if(hit(pb,it)){collect(it);state.items.splice(i,1)}else if(it.x+it.w<-40)state.items.splice(i,1)}
 for(let i=state.shots.length-1;i>=0;i--){const s=state.shots[i];let used=false;for(let j=state.objects.length-1;j>=0;j--){if(hit(s,objectBox(state.objects[j]))){const o=state.objects[j];state.score+=90;burst(o.x+o.w/2,o.y+o.h/2,'#7ef7ff',12);state.objects.splice(j,1);used=true;break}}if(used||s.x>W+80||s.life<=0)state.shots.splice(i,1)}
 for(const p of state.particles){p.x+=p.vx*dt;p.y+=p.vy*dt;p.vy+=500*dt;p.life-=dt}state.particles=state.particles.filter(p=>p.life>0);for(const f of state.floaters){f.y+=f.vy*dt;f.life-=dt}state.floaters=state.floaters.filter(f=>f.life>0);
 if(state.score>=GOAL&&!state.won){state.won=true;state.high=Math.max(state.high,Math.floor(state.score));localStorage.setItem('rexRemixHigh',state.high);showOverlay('Backyard Complete!',`Rex cleared the illustrated Backyard with ${state.lives} ${state.lives===1?'life':'lives'} remaining.`,'Play Again')}
 updateHud()}
function drawBackground(){const t=state.distance;const sky=ctx.createLinearGradient(0,0,0,G);sky.addColorStop(0,'#56c9ff');sky.addColorStop(1,'#dff8ff');ctx.fillStyle=sky;ctx.fillRect(0,0,W,G);ctx.fillStyle='rgba(255,255,255,.75)';drawCloud(120-(t*.025)%1150,92,1);drawCloud(610-(t*.018)%1200,120,.8);drawCloud(920-(t*.03)%1300,70,.65);ctx.fillStyle='#8bc66a';for(let x=-180-(t*.07)%260;x<W+260;x+=220){ctx.beginPath();ctx.arc(x,310,170,0,Math.PI*2);ctx.fill()}for(let x=-220-(t*.11)%350;x<W+350;x+=330)drawHouse(x,252);ctx.fillStyle='#6aa94e';ctx.fillRect(0,338,W,100);for(let x=-90-(t*.22)%92;x<W+92;x+=92)drawFence(x,330);ctx.fillStyle='#4c9d36';ctx.fillRect(0,402,W,36);ctx.fillStyle='#70ca42';for(let x=0;x<W;x+=24){ctx.beginPath();ctx.moveTo(x,G);ctx.lineTo(x+8,G-18);ctx.lineTo(x+16,G);ctx.fill()}ctx.fillStyle='#744225';ctx.fillRect(0,G,W,H-G);ctx.fillStyle='rgba(63,31,18,.32)';for(let x=-40-(t*.8)%120;x<W+120;x+=120){ctx.beginPath();ctx.ellipse(x,G+48,18,7,0,0,Math.PI*2);ctx.fill();ctx.beginPath();ctx.ellipse(x+48,G+90,12,5,0,0,Math.PI*2);ctx.fill()}}
function drawCloud(x,y,s){ctx.beginPath();ctx.arc(x,y,30*s,0,Math.PI*2);ctx.arc(x+32*s,y-12*s,40*s,0,Math.PI*2);ctx.arc(x+70*s,y,32*s,0,Math.PI*2);ctx.fill()}
function drawHouse(x,y){ctx.fillStyle='#f2ddb3';ctx.fillRect(x,y,135,88);ctx.fillStyle='#b84b38';ctx.beginPath();ctx.moveTo(x-12,y);ctx.lineTo(x+67,y-48);ctx.lineTo(x+147,y);ctx.fill();ctx.fillStyle='#67b9dc';ctx.fillRect(x+22,y+30,28,35);ctx.fillRect(x+86,y+30,28,35)}
function drawFence(x,y){ctx.fillStyle='#fff4cf';ctx.strokeStyle='#c7a875';ctx.lineWidth=2;ctx.beginPath();ctx.moveTo(x,70);ctx.lineTo(x+32,0);ctx.lineTo(x+64,70);ctx.closePath();ctx.fill();ctx.stroke();ctx.fillRect(x,32,64,70);ctx.strokeRect(x,32,64,70)}
function drawImageFit(im,x,y,w,h,flip=false){if(!im)return;ctx.save();if(flip){ctx.translate(x+w,y);ctx.scale(-1,1);ctx.drawImage(im,0,0,w,h)}else ctx.drawImage(im,x,y,w,h);ctx.restore()}
function drawPlayer(){const im=images.rexJump||images.rexRun;if(!im)return;ctx.save();if(player.inv>0&&Math.floor(player.inv*12)%2)ctx.globalAlpha=.35;const running=player.ground;const stride=Math.sin(player.anim*11);const bob=running?Math.abs(stride)*4:0;const tilt=running?-.055:Math.max(-.13,Math.min(.13,player.vy/4200));ctx.translate(player.x+player.w/2,player.y+player.h/2+bob+2);ctx.rotate(tilt);ctx.scale(running?1+stride*.012:1,running?.88-stride*.012:1);drawImageFit(im,-player.w/2,-player.h/2,player.w,player.h);ctx.restore();if(player.shield){const pulse=1+Math.sin(player.anim*8)*.025;ctx.strokeStyle='rgba(70,218,255,.96)';ctx.fillStyle='rgba(70,218,255,.12)';ctx.lineWidth=5;ctx.beginPath();ctx.ellipse(player.x+player.w/2,player.y+player.h/2,player.w*.57*pulse,player.h*.59*pulse,0,0,Math.PI*2);ctx.fill();ctx.stroke()}}
function drawObstacle(o){const d=obstacleDefs[o.type],im=images[d.image];let y=o.y;if(o.type==='cat')y+=Math.sin(o.phase)*2;if(o.type==='duck')y+=Math.sin(o.phase*1.3)*4;drawImageFit(im,o.x,y,o.w,o.h)}
function drawItem(it){const cx=it.x+it.w/2,cy=it.y+27,pulse=1+Math.sin(it.phase)*.055;ctx.save();ctx.translate(cx,cy);ctx.scale(pulse,pulse);ctx.shadowColor='rgba(0,0,0,.28)';ctx.shadowBlur=10;ctx.shadowOffsetY=5;const fill={star:'#ffd735',shield:'#39c8ff',laser:'#42d45a',roar:'#ff625d'}[it.kind];ctx.fillStyle=fill;ctx.strokeStyle='#fff';ctx.lineWidth=4;ctx.beginPath();ctx.arc(0,0,26,0,Math.PI*2);ctx.fill();ctx.stroke();ctx.shadowColor='transparent';ctx.strokeStyle='#12324d';ctx.fillStyle='#12324d';ctx.lineWidth=4;ctx.lineCap='round';ctx.lineJoin='round';if(it.kind==='star'){ctx.beginPath();for(let i=0;i<10;i++){const a=-Math.PI/2+i*Math.PI/5,r=i%2?10:21;const px=Math.cos(a)*r,py=Math.sin(a)*r;i?ctx.lineTo(px,py):ctx.moveTo(px,py)}ctx.closePath();ctx.fill()}else if(it.kind==='shield'){ctx.beginPath();ctx.moveTo(0,-18);ctx.lineTo(17,-11);ctx.lineTo(14,8);ctx.quadraticCurveTo(10,20,0,24);ctx.quadraticCurveTo(-10,20,-14,8);ctx.lineTo(-17,-11);ctx.closePath();ctx.fill();ctx.strokeStyle='rgba(255,255,255,.8)';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(0,-12);ctx.lineTo(0,15);ctx.stroke()}else if(it.kind==='laser'){ctx.fillRect(-18,-6,29,12);ctx.beginPath();ctx.moveTo(8,-10);ctx.lineTo(22,-5);ctx.lineTo(22,5);ctx.lineTo(8,10);ctx.closePath();ctx.fill();ctx.fillRect(-8,6,8,13);ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(25,0);ctx.lineTo(34,0);ctx.stroke()}else{ctx.beginPath();ctx.moveTo(-17,8);ctx.quadraticCurveTo(-17,-12,-2,-15);ctx.quadraticCurveTo(13,-17,18,-5);ctx.lineTo(9,-3);ctx.lineTo(17,4);ctx.quadraticCurveTo(4,18,-12,12);ctx.closePath();ctx.fill();ctx.strokeStyle='#fff';ctx.lineWidth=3;ctx.beginPath();ctx.arc(-3,-5,2,0,Math.PI*2);ctx.stroke();ctx.beginPath();ctx.arc(5,2,11,-.6,.65);ctx.stroke()}ctx.restore();const label={star:'BONUS',shield:'SHIELD',laser:'LASER',roar:'ROAR'}[it.kind];ctx.font='900 12px system-ui';ctx.textAlign='center';ctx.textBaseline='middle';const tw=ctx.measureText(label).width+18;ctx.fillStyle='rgba(5,30,52,.92)';roundRect(ctx,cx-tw/2,it.y+55,tw,21,10);ctx.fill();ctx.fillStyle='#fff';ctx.fillText(label,cx,it.y+65)}
function roundRect(c,x,y,w,h,r){c.beginPath();c.moveTo(x+r,y);c.arcTo(x+w,y,x+w,y+h,r);c.arcTo(x+w,y+h,x,y+h,r);c.arcTo(x,y+h,x,y,r);c.arcTo(x,y,x+w,y,r);c.closePath()}
function draw(){ctx.clearRect(0,0,W,H);drawBackground();for(const it of state.items)drawItem(it);for(const o of state.objects)drawObstacle(o);for(const s of state.shots){ctx.fillStyle='#66f4ff';ctx.fillRect(s.x,s.y,s.w,s.h);ctx.fillStyle='#fff';ctx.fillRect(s.x+10,s.y+2,s.w-18,s.h-4)}drawPlayer();for(const p of state.particles){ctx.globalAlpha=Math.max(0,p.life/.8);ctx.fillStyle=p.color;ctx.beginPath();ctx.arc(p.x,p.y,p.size,0,Math.PI*2);ctx.fill()}ctx.globalAlpha=1;for(const f of state.floaters){ctx.globalAlpha=Math.max(0,f.life);ctx.fillStyle=f.color;ctx.strokeStyle='rgba(0,0,0,.65)';ctx.lineWidth=4;ctx.font='900 20px system-ui';ctx.textAlign='center';ctx.strokeText(f.text,f.x,f.y);ctx.fillText(f.text,f.x,f.y)}ctx.globalAlpha=1;ctx.textAlign='left';if(!assetsReady){ctx.fillStyle='rgba(4,20,38,.7)';ctx.fillRect(0,0,W,H);ctx.fillStyle='#fff';ctx.font='800 25px system-ui';ctx.textAlign='center';ctx.fillText('Loading illustrated Rex and obstacles…',W/2,H/2)}}
function loop(ms){const dt=Math.min(.033,(ms-state.last)/1000||0);state.last=ms;update(dt);draw();requestAnimationFrame(loop)}
function openInstructions(){ui.instructions.classList.remove('hidden');if(state.mode==='play')state.mode='pause'}
function closeInstructions(){ui.instructions.classList.add('hidden');if(!ui.overlay.classList.contains('visible')){state.mode='play';state.last=performance.now()}}
const stopGesture=e=>{if(e.cancelable)e.preventDefault()};document.addEventListener('touchmove',stopGesture,{passive:false});document.addEventListener('gesturestart',stopGesture,{passive:false});document.addEventListener('gesturechange',stopGesture,{passive:false});window.addEventListener('scroll',()=>window.scrollTo(0,0),{passive:true});
ui.start.addEventListener('click',()=>{if(state.mode==='pause')pause();else reset()});ui.jump.addEventListener('pointerdown',e=>{e.preventDefault();jumpDown()});ui.jump.addEventListener('pointerup',jumpUp);ui.jump.addEventListener('pointercancel',jumpUp);canvas.addEventListener('pointerdown',e=>{e.preventDefault();jumpDown()});canvas.addEventListener('pointerup',jumpUp);canvas.addEventListener('pointercancel',jumpUp);ui.shoot.addEventListener('pointerdown',e=>{e.preventDefault();shoot()});ui.roar.addEventListener('pointerdown',e=>{e.preventDefault();roar()});ui.pause.addEventListener('click',pause);$('instructionsBtn').addEventListener('click',openInstructions);$('overlayInstructionsBtn').addEventListener('click',openInstructions);$('closeInstructionsBtn').addEventListener('click',closeInstructions);ui.sound.addEventListener('click',()=>{state.sound=!state.sound;localStorage.setItem('rexRemixSound',state.sound);ui.sound.textContent=state.sound?'Sound On':'Sound Off';ui.sound.setAttribute('aria-pressed',String(state.sound))});addEventListener('keydown',e=>{if(e.code==='Space'||e.code==='ArrowUp'){e.preventDefault();if(!e.repeat)jumpDown()}else if(e.code==='KeyF'||e.code==='KeyX')shoot();else if(e.code==='KeyR')roar();else if(e.code==='Escape'||e.code==='KeyP')pause()});addEventListener('keyup',e=>{if(e.code==='Space'||e.code==='ArrowUp')jumpUp()});document.addEventListener('visibilitychange',()=>{if(document.hidden&&state.mode==='play')pause()});
ui.high.textContent=state.high.toLocaleString();ui.sound.textContent=state.sound?'Sound On':'Sound Off';updateHud();requestAnimationFrame(loop);
})();
